package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strings"

	"go.mongodb.org/mongo-driver/bson"
)

func (r *clientResolver) Sites(ctx context.Context, obj *ClientGQL) ([]*SiteGQL, error) {
	cursor, err := SiteCollection.Find(ctx, bson.M{"client_id": obj.ClientID})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch sites for client: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*SiteGQL
	for cursor.Next(ctx) {
		var s Site
		if err := cursor.Decode(&s); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toSiteGQL(&s))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *deviceInstanceResolver) Sensors(ctx context.Context, obj *DeviceInstanceGQL) ([]*SensorGQL, error) {
	sensorID := obj.DeviceInstanceID
	if strings.HasPrefix(sensorID, "device_instance") {
		sensorID = strings.Replace(sensorID, "device_instance", "sensor", 1)
	} else if strings.Contains(sensorID, "_device_instance_") {
		sensorID = strings.Replace(sensorID, "_device_instance_", "_sensor_", 1)
	}

	cursor, err := SensorCollection.Find(ctx, bson.M{
		"$or": []bson.M{
			{"device_instance_id": obj.DeviceInstanceID},
			{"device_instance_id": sensorID},
			{"_id": sensorID},
			{"_id": obj.DeviceInstanceID},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch sensors for device instance: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*SensorGQL
	seen := make(map[string]bool)
	for cursor.Next(ctx) {
		var s Sensor
		if err := cursor.Decode(&s); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		if !seen[s.ID] {
			seen[s.ID] = true
			results = append(results, toSensorGQL(&s))
		}
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *deviceInstanceResolver) GatewayInstance(ctx context.Context, obj *DeviceInstanceGQL) (*GatewayInstanceGQL, error) {
	if obj.GatewayInstanceID != nil && *obj.GatewayInstanceID != "" {
		var gi GatewayInstance
		err := GatewayInstanceCollection.FindOne(ctx, bson.M{"gateway_instance_id": *obj.GatewayInstanceID}).Decode(&gi)
		if err == nil {
			return toGatewayInstanceGQL(&gi), nil
		}
	}

	sensorID := obj.DeviceInstanceID
	if strings.HasPrefix(sensorID, "device_instance") {
		sensorID = strings.Replace(sensorID, "device_instance", "sensor", 1)
	} else if strings.Contains(sensorID, "_device_instance_") {
		sensorID = strings.Replace(sensorID, "_device_instance_", "_sensor_", 1)
	}

	var s Sensor
	err := SensorCollection.FindOne(ctx, bson.M{
		"$or": []bson.M{
			{"device_instance_id": obj.DeviceInstanceID},
			{"device_instance_id": sensorID},
			{"_id": sensorID},
			{"_id": obj.DeviceInstanceID},
		},
	}).Decode(&s)
	if err == nil && s.GeneralInfo.GatewayInstanceID != "" {
		var gi GatewayInstance
		err = GatewayInstanceCollection.FindOne(ctx, bson.M{"gateway_instance_id": s.GeneralInfo.GatewayInstanceID}).Decode(&gi)
		if err == nil {
			return toGatewayInstanceGQL(&gi), nil
		}
	}

	return nil, nil
}

func (r *gatewayResolver) Site(ctx context.Context, obj *GatewayGQL) (*SiteGQL, error) {
	var s Site
	err := SiteCollection.FindOne(ctx, bson.M{"$or": []bson.M{
		{"site_id": obj.SiteID},
		{"industry_id": obj.SiteID},
		{"_id": obj.SiteID},
	}}).Decode(&s)
	if err != nil {
		return nil, fmt.Errorf("site not found for gateway: %w", err)
	}
	return toSiteGQL(&s), nil
}

func (r *gatewayResolver) DeviceInstances(ctx context.Context, obj *GatewayGQL) ([]*DeviceInstanceGQL, error) {
	cursor, err := DeviceInstanceCollection.Find(ctx, bson.M{"gateway_id": obj.GatewayID})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch device instances for gateway: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*DeviceInstanceGQL
	for cursor.Next(ctx) {
		var d DeviceInstance
		if err := cursor.Decode(&d); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toDeviceInstanceGQL(&d))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *gatewayInstanceResolver) Site(ctx context.Context, obj *GatewayInstanceGQL) (*SiteGQL, error) {
	var s Site
	err := SiteCollection.FindOne(ctx, bson.M{"$or": []bson.M{
		{"site_id": obj.SiteID},
		{"industry_id": obj.SiteID},
		{"_id": obj.SiteID},
	}}).Decode(&s)
	if err != nil {
		return nil, nil
	}
	return toSiteGQL(&s), nil
}

func (r *gatewayInstanceResolver) DeviceInstances(ctx context.Context, obj *GatewayInstanceGQL) ([]*DeviceInstanceGQL, error) {
	var deviceIDs []string

	sensorCursor, err := SensorCollection.Find(ctx, bson.M{"general_info.gateway_instance_id": obj.GatewayInstanceID})
	if err == nil {
		defer sensorCursor.Close(ctx)
		for sensorCursor.Next(ctx) {
			var s Sensor
			if err := sensorCursor.Decode(&s); err == nil {
				devID := s.DeviceInstanceID
				if strings.HasPrefix(devID, "sensor") {
					devID = strings.Replace(devID, "sensor", "device_instance", 1)
				} else if strings.Contains(devID, "_sensor_") {
					devID = strings.Replace(devID, "_sensor_", "_device_instance_", 1)
				}
				if devID != "" {
					deviceIDs = append(deviceIDs, devID)
				}
			}
		}
	}

	filter := bson.M{
		"$or": []bson.M{
			{"gateway_instance_id": obj.GatewayInstanceID},
		},
	}
	if len(deviceIDs) > 0 {
		filter["$or"] = append(filter["$or"].([]bson.M), bson.M{"device_instance_id": bson.M{"$in": deviceIDs}})
		filter["$or"] = append(filter["$or"].([]bson.M), bson.M{"_id": bson.M{"$in": deviceIDs}})
	}

	cursor, err := DeviceInstanceCollection.Find(ctx, filter)
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var results []*DeviceInstanceGQL
	seen := make(map[string]bool)
	for cursor.Next(ctx) {
		var d DeviceInstance
		if err := cursor.Decode(&d); err != nil {
			return nil, err
		}
		if !seen[d.ID] {
			seen[d.ID] = true
			results = append(results, toDeviceInstanceGQL(&d))
		}
	}
	return results, nil
}

func (r *queryResolver) Users(ctx context.Context) ([]*UserGQL, error) {
	cursor, err := UserCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch users: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*UserGQL
	for cursor.Next(ctx) {
		var u User
		if err := cursor.Decode(&u); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toGQL(&u))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *queryResolver) User(ctx context.Context, id string) (*UserGQL, error) {
	var u User
	err := UserCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&u)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}
	return toGQL(&u), nil
}

func (r *queryResolver) DeviceInstances(ctx context.Context) ([]*DeviceInstanceGQL, error) {
	cursor, err := DeviceInstanceCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch device instances: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*DeviceInstanceGQL
	for cursor.Next(ctx) {
		var d DeviceInstance
		if err := cursor.Decode(&d); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toDeviceInstanceGQL(&d))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *queryResolver) DeviceInstance(ctx context.Context, id string) (*DeviceInstanceGQL, error) {
	var d DeviceInstance
	err := DeviceInstanceCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&d)
	if err != nil {
		return nil, fmt.Errorf("device instance not found: %w", err)
	}
	return toDeviceInstanceGQL(&d), nil
}

func (r *queryResolver) DeviceModels(ctx context.Context) ([]*DeviceModelGQL, error) {
	cursor, err := DeviceModelCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch device models: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*DeviceModelGQL
	for cursor.Next(ctx) {
		var m DeviceModel
		if err := cursor.Decode(&m); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toDeviceModelGQL(&m))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *queryResolver) DeviceModel(ctx context.Context, id string) (*DeviceModelGQL, error) {
	var m DeviceModel
	err := DeviceModelCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&m)
	if err != nil {
		return nil, fmt.Errorf("device model not found: %w", err)
	}
	return toDeviceModelGQL(&m), nil
}

func (r *queryResolver) Sensors(ctx context.Context) ([]*SensorGQL, error) {
	cursor, err := SensorCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch sensors: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*SensorGQL
	for cursor.Next(ctx) {
		var s Sensor
		if err := cursor.Decode(&s); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toSensorGQL(&s))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *queryResolver) Sensor(ctx context.Context, id string) (*SensorGQL, error) {
	var s Sensor
	err := SensorCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&s)
	if err != nil {
		return nil, fmt.Errorf("sensor not found: %w", err)
	}
	return toSensorGQL(&s), nil
}

func (r *queryResolver) Batches(ctx context.Context) ([]*BatchGQL, error) {
	cursor, err := BatchCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch batches: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*BatchGQL
	for cursor.Next(ctx) {
		var b Batch
		if err := cursor.Decode(&b); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toBatchGQL(&b))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *queryResolver) Batch(ctx context.Context, id string) (*BatchGQL, error) {
	var b Batch
	err := BatchCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&b)
	if err != nil {
		return nil, fmt.Errorf("batch not found: %w", err)
	}
	return toBatchGQL(&b), nil
}

func (r *queryResolver) Clients(ctx context.Context) ([]*ClientGQL, error) {
	cursor, err := ClientCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch clients: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*ClientGQL
	for cursor.Next(ctx) {
		var c Client
		if err := cursor.Decode(&c); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toClientGQL(&c))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *queryResolver) Client(ctx context.Context, id string) (*ClientGQL, error) {
	var c Client
	err := ClientCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&c)
	if err != nil {
		return nil, fmt.Errorf("client not found: %w", err)
	}
	return toClientGQL(&c), nil
}

func (r *queryResolver) Costs(ctx context.Context) ([]*CostGQL, error) {
	cursor, err := CostCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch costs: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*CostGQL
	for cursor.Next(ctx) {
		var c Cost
		if err := cursor.Decode(&c); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toCostGQL(&c))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *queryResolver) Cost(ctx context.Context, id string) (*CostGQL, error) {
	var c Cost
	err := CostCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&c)
	if err != nil {
		return nil, fmt.Errorf("cost not found: %w", err)
	}
	return toCostGQL(&c), nil
}
func (r *queryResolver) Sites(ctx context.Context) ([]*SiteGQL, error) {
	cursor, err := SiteCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch sites: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*SiteGQL
	for cursor.Next(ctx) {
		var s Site
		if err := cursor.Decode(&s); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toSiteGQL(&s))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

// Site is the resolver for the site field.
func (r *queryResolver) Site(ctx context.Context, id string) (*SiteGQL, error) {
	var s Site
	err := SiteCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&s)
	if err != nil {
		return nil, fmt.Errorf("site not found: %w", err)
	}
	return toSiteGQL(&s), nil
}

func (r *queryResolver) Gateways(ctx context.Context) ([]*GatewayGQL, error) {
	cursor, err := GatewayCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch gateways: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*GatewayGQL
	for cursor.Next(ctx) {
		var g Gateway
		if err := cursor.Decode(&g); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toGatewayGQL(&g))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *queryResolver) Gateway(ctx context.Context, id string) (*GatewayGQL, error) {
	var g Gateway
	err := GatewayCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&g)
	if err != nil {
		return nil, fmt.Errorf("gateway not found: %w", err)
	}
	return toGatewayGQL(&g), nil
}

func (r *queryResolver) GatewayInstances(ctx context.Context) ([]*GatewayInstanceGQL, error) {
	cursor, err := GatewayInstanceCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch gateway instances: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*GatewayInstanceGQL
	for cursor.Next(ctx) {
		var gi GatewayInstance
		if err := cursor.Decode(&gi); err != nil {
			return nil, err
		}
		results = append(results, toGatewayInstanceGQL(&gi))
	}
	return results, nil
}

func (r *queryResolver) GatewayInstance(ctx context.Context, id string) (*GatewayInstanceGQL, error) {
	var gi GatewayInstance
	err := GatewayInstanceCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&gi)
	if err != nil {
		return nil, fmt.Errorf("gateway instance not found: %w", err)
	}
	return toGatewayInstanceGQL(&gi), nil
}

func (r *queryResolver) AlarmConfigurations(ctx context.Context) ([]*AlarmConfigurationGQL, error) {
	cursor, err := AlarmConfigurationCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch alarm configurations: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*AlarmConfigurationGQL
	for cursor.Next(ctx) {
		var ac AlarmConfiguration
		if err := cursor.Decode(&ac); err != nil {
			return nil, err
		}
		results = append(results, toAlarmConfigurationGQL(&ac))
	}
	return results, nil
}

func (r *queryResolver) AlarmConfiguration(ctx context.Context, id string) (*AlarmConfigurationGQL, error) {
	var ac AlarmConfiguration
	err := AlarmConfigurationCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&ac)
	if err != nil {
		return nil, fmt.Errorf("alarm configuration not found: %w", err)
	}
	return toAlarmConfigurationGQL(&ac), nil
}

func (r *queryResolver) BillMasters(ctx context.Context) ([]*BillMasterGQL, error) {
	cursor, err := BillMasterCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch bill masters: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*BillMasterGQL
	for cursor.Next(ctx) {
		var bm BillMaster
		if err := cursor.Decode(&bm); err != nil {
			return nil, err
		}
		results = append(results, toBillMasterGQL(&bm))
	}
	return results, nil
}

func (r *queryResolver) BillMaster(ctx context.Context, id string) (*BillMasterGQL, error) {
	var bm BillMaster
	err := BillMasterCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&bm)
	if err != nil {
		return nil, fmt.Errorf("bill master not found: %w", err)
	}
	return toBillMasterGQL(&bm), nil
}

func (r *queryResolver) EmailGateways(ctx context.Context) ([]*EmailGatewayGQL, error) {
	cursor, err := EmailGatewayCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch email gateways: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*EmailGatewayGQL
	for cursor.Next(ctx) {
		var eg EmailGateway
		if err := cursor.Decode(&eg); err != nil {
			return nil, err
		}
		results = append(results, toEmailGatewayGQL(&eg))
	}
	return results, nil
}
func (r *queryResolver) EmailGateway(ctx context.Context, id string) (*EmailGatewayGQL, error) {
	var eg EmailGateway
	err := EmailGatewayCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&eg)
	if err != nil {
		return nil, fmt.Errorf("email gateway not found: %w", err)
	}
	return toEmailGatewayGQL(&eg), nil
}

func (r *queryResolver) WorkGroups(ctx context.Context) ([]*WorkGroupGQL, error) {
	cursor, err := WorkGroupCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch work groups: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*WorkGroupGQL
	for cursor.Next(ctx) {
		var wg WorkGroup
		if err := cursor.Decode(&wg); err != nil {
			return nil, err
		}
		results = append(results, toWorkGroupGQL(&wg))
	}
	return results, nil
}

func (r *queryResolver) WorkGroup(ctx context.Context, id string) (*WorkGroupGQL, error) {
	var wg WorkGroup
	err := WorkGroupCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&wg)
	if err != nil {
		return nil, fmt.Errorf("work group not found: %w", err)
	}
	return toWorkGroupGQL(&wg), nil

func (r *queryResolver) SmartMeterConfigurations(ctx context.Context) ([]*SmartMeterConfigurationGQL, error) {
	cursor, err := SmartMeterConfigurationCollection.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch smart meter configurations: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*SmartMeterConfigurationGQL
	for cursor.Next(ctx) {
		var sm SmartMeterConfiguration
		if err := cursor.Decode(&sm); err != nil {
			return nil, err
		}
		results = append(results, toSmartMeterConfigurationGQL(&sm))
	}
	return results, nil
}

func (r *queryResolver) SmartMeterConfiguration(ctx context.Context, id string) (*SmartMeterConfigurationGQL, error) {
	var sm SmartMeterConfiguration
	err := SmartMeterConfigurationCollection.FindOne(ctx, bson.M{"_id": id}).Decode(&sm)
	if err != nil {
		return nil, fmt.Errorf("smart meter configuration not found: %w", err)
	}
	return toSmartMeterConfigurationGQL(&sm), nil
}

func (r *siteResolver) Client(ctx context.Context, obj *SiteGQL) (*ClientGQL, error) {
	var c Client
	err := ClientCollection.FindOne(ctx, bson.M{"client_id": obj.ClientID}).Decode(&c)
	if err != nil {
		return nil, fmt.Errorf("client not found for site: %w", err)
	}
	return toClientGQL(&c), nil
}

func (r *siteResolver) Gateways(ctx context.Context, obj *SiteGQL) ([]*GatewayGQL, error) {
	cursor, err := GatewayCollection.Find(ctx, bson.M{"site_id": obj.SiteID})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch gateways for site: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*GatewayGQL
	for cursor.Next(ctx) {
		var g Gateway
		if err := cursor.Decode(&g); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toGatewayGQL(&g))
	}
	if err := cursor.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

func (r *siteResolver) GatewayInstances(ctx context.Context, obj *SiteGQL) ([]*GatewayInstanceGQL, error) {
	cursor, err := GatewayInstanceCollection.Find(ctx, bson.M{"site_id": obj.SiteID})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch gateway instances for site: %w", err)
	}
	defer cursor.Close(ctx)

	var results []*GatewayInstanceGQL
	for cursor.Next(ctx) {
		var gi GatewayInstance
		if err := cursor.Decode(&gi); err != nil {
			return nil, fmt.Errorf("decode error: %w", err)
		}
		results = append(results, toGatewayInstanceGQL(&gi))
	}
	return results, nil
}

func (r *Resolver) Client() ClientResolver { return &clientResolver{r} }
func (r *Resolver) DeviceInstance() DeviceInstanceResolver { return &deviceInstanceResolver{r} }

func (r *Resolver) Gateway() GatewayResolver { return &gatewayResolver{r} }
func (r *Resolver) GatewayInstance() GatewayInstanceResolver { return &gatewayInstanceResolver{r} }
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }
func (r *Resolver) Site() SiteResolver { return &siteResolver{r} }

type clientResolver struct{ *Resolver }
type deviceInstanceResolver struct{ *Resolver }
type gatewayResolver struct{ *Resolver }
type gatewayInstanceResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type siteResolver struct{ *Resolver }
